### PR TITLE
Get object classname

### PR DESCRIPTION
**Pull request by marc1006**
It's useful:
- if you have a reference to an object and you don't know the class of it
- if you call a generic method in Java and you want to determine the class of the result
- to determine the real class if it's type is an interface

```
...
let instance = Dalvik.cast(p, klass);
console.log(instance.constructor.name);
console.log(instance.class);
console.log(Dalvik.getObjectClassname(instance));
console.log(Dalvik.getObjectClassname(p));
```

Results
```
ITest
interface com.example.example.ITest
com.example.example.Test1
com.example.example.Test1
```

### CODE REVIEW

**Comment by Tyilo** [comment]
How about using `instance.$className` to match Objective-C instances?

**Comment by oleavr** [comment]
Nice! Yes, +1 on the suggestion from @Tyilo, we should try to stick to the same convention that we use in ObjC.

**Comment by marc1006** [comment]
Okay - I will add it in this way.
And what should we do if we have only the (jobject) reference to it? (and nothing else)

**Comment by oleavr** [comment]
Cool. In that case we need a way to construct an object wrapper from a `jobject`.

**Comment by oleavr** [comment]
Sweet! Thanks!

**Pull request merged**
