### PR TITLE
Fix trailing junk data in ansi_string_to_utf8

### PR DESCRIPTION
**Pull request by clouds56**
See the [doc](https://docs.microsoft.com/en-us/windows/desktop/api/stringapiset/nf-stringapiset-multibytetowidechar)

### CODE REVIEW

**Comment by clouds56** [comment]
Haven't been tested, just proposing the change and needs review.

**Comment by oleavr** [comment]
Good catch. Please write a test-case demonstrating the desired behavior.

**Comment by clouds56** [comment]
I think it is a little complicate to test this behavior, the CP_ACP value differs between computers. The issue would only occurs in the CodePages that have [multi-bytes](https://docs.microsoft.com/en-us/windows/desktop/intl/double-byte-character-sets). (cp1250 for english is [single byte](https://docs.microsoft.com/en-us/windows/desktop/intl/single-byte-character-sets) codepage).

**Comment by clouds56** [comment]
I add a test case (and flag G_OS_ACP_936 to enable).
There's no guide for build and test, so I haven't tried it myself. (why is there no CI for the repo?)

**Comment by oleavr** [comment]
Thank you! Sorry for the delay here.

We do have a CI but it's not yet wired up to GitHub. Could you try running this test locally? All you need is VS2017 (Community edition will do), then run `gum-tests`, and to run only one test pass it `-p /Path/to/test`.

**Comment by oleavr** [comment]
Timed out. Please reopen in the future if you find the time to look into this.

**Comment by oleavr** [comment]
Actually let me take a quick look at this now, as I need to land another PR on Windows.

**Comment by oleavr** [comment]
Finalized version landed in cdf6643225cc45a004bb0c5cf7d22b2a28e59cb0. Thanks for reporting and helping fix this! ❤️

**Pull request closed without merging**
