### PR TITLE
Switch from fopen to open for memory read/writes

### PR DESCRIPTION
**Pull request by s1341**
fopen/fread/fwrite might be buffered, open/read/write is not. This was causing an issue where there was a partial read when doing the 'copy on mprotect to write' in gum_try_mprotect.

### CODE REVIEW

**Comment by s1341** [comment]
I forgot that I also switched the allocation in gum_try_mprotect to be an alloca instead of malloc. This is because we're encountering fail when trying to Intercept malloc itself.

**Comment by oleavr** [comment]
Nice. I suppose lack of EINTR handling isn't a big deal?

**Comment by s1341** [comment]
Yeah. I think the likelihood of EINTR is low. I don't want to add handling until I see it actually occur in the wild.

**Comment by oleavr** [comment]
:+1:

**Pull request merged**
