### PR TITLE
Fix ThumbRelocator IT block eoi logic

### PR DESCRIPTION
**Pull request by bet4it**
Just borrow the variable `self->it_block.active` as a flag.

### CODE REVIEW

**Comment by oleavr** [comment]
Thanks! What does this solve for you?

**Comment by bet4it** [comment]
I add a test about it.

**Comment by oleavr** [comment]
@bet4it Thanks! This breaks the Stalker ARM32 test-suite. You can run it like this: `./tests/run-android-arm.sh -p /Core/Stalker`

**Comment by bet4it** [comment]
I don't have macOS, sad😅
https://github.com/frida/frida-gum/blob/58888455b404aeb5bfe0bf7dad2442097fc473de/tests/run-android-arm.sh#L10

**Comment by oleavr** [comment]
@bet4it Replace that with linux if you're on Linux. It's a (bit too) dumb script 😄

**Comment by bet4it** [comment]
Now all the tests have passed. What do you think about it?

**Comment by oleavr** [comment]
Thanks! (Merged with a few minor style tweaks.)

**Pull request merged**
