### PR TITLE
Docstrings

### PR DESCRIPTION
**Pull request by Fitblip**
Initial pass at docstrings & a small tweak to gum_script_memory_on_copy to match memcpy()

:smiley:

### CODE REVIEW

**Comment by oleavr** [comment]
Woohoo, so awesome!

What do you think about tweaking the comments to look a bit more like the regular ones? So instead of:

```
/*
Prototype: 
WeakRef.bind(target, callback_val)

Docs:
TBW

Example:
TBW
*/
```

we go:

```
/*
 * Prototype: 
 * WeakRef.bind(target, callback_val)
 *
 * Docs:
 * TBW
 *
 * Example:
 * TBW
 */
```

**Comment by Fitblip** [comment]
Sure! I'll work on that tomorrow (it's almost 4AM here) and push a revised commit.

**Comment by oleavr** [comment]
Sweet!

**Comment by Fitblip** [comment]
Updated! Now for reals I'm going to sleep :+1:

**Comment by oleavr** [comment]
Sweet! :+1: Before we land, could we strip off the trailing whitespace on the empty lines?

**Comment by oleavr** [comment]
Thanks, merged!

**Pull request merged**
