### PR TITLE
Fix all ObjC types

### PR DESCRIPTION
**Pull request by Tyilo**
The test still fails, even though it works if I run it using `frida foo -l test.js` (replacing `send` with `console.log`).

### CODE REVIEW

**Comment by oleavr** [comment]
Awesome! Just one nitpick; could you change "function()" to "function ()" (for consistency with "function foo()"? Cheers!

**Comment by Tyilo** [comment]
Sure.

Do you know why the test fails, when it works when loading the script in
the frida repl?

On Friday, May 8, 2015, Ole André Vadla Ravnås <notifications@github.com>
wrote:

> Awesome! Just one nitpick; could you change "function()" to "function ()"
> (for consistency with "function foo()"? Cheers!
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/frida/frida-gum/pull/44#issuecomment-100326543>.
>


-- 
Asger Hautop Drewsen

**Comment by oleavr** [comment]
Hmm, could it be an escaping issue? (JS inline in C strings.)

**Comment by oleavr** [comment]
Thanks! Merged.

**Pull request merged**
