### PR TITLE
Optimize ObjC's ClassFactory.refresh

### PR DESCRIPTION
**Pull request by Tyilo**
It now does nothing if the number of classes hasn't changed.

### CODE REVIEW

**Comment by Tyilo** [comment]
Maybe we should just call `ObjC.refreshClasses` automatically now every time a class is requested?

**Comment by oleavr** [comment]
Sweet! Just one coding style nitpick and this is ready to land (space after `if`).

**Comment by oleavr** [comment]
Yeah, that sounds good to me (as long as it's not in the cache).

**Comment by Tyilo** [comment]
Yeah, but then it should probably be removed from the public API.

**Comment by oleavr** [comment]
Agreed. Let's do that and bump the major version for the next release. (Also planned is renaming `frida-repl` to just `frida` so timing is good.)

**Pull request merged**
